export const state = {
  api: null,
  user: null,
  myStream: null,
  channelInfo: null,
  twitchTrackerSummary: null,
  recentVods: [],
  selectedPreviousVodId: null,
  offlineCategorySelection: null,
  offlineCategoryCleared: false,
  usingPreviousStream: false,
  myTeams: [], // Twitch Teams the logged-in user belongs to
  matches: [],
  extraCategories: [], // additional {id, name} categories to include, beyond myStream's own game
  expandedWatchId: null, // user_id of the result card currently showing a live embed, if any
  expandedActivityId: null,
  raidListener: null,
  followStatusWarningShown: false,
  chatSettingsWarningShown: false,
  contentLabelsWarningShown: false,
  resultsPage: 1,
  resultsPageSize: 12,
  resultsSort: 'following-first',
  resultsMode: 'matches',
  activeRaid: null,
  raidCountdownTimer: null,
  raidCompletionInProgress: false,
  searchAbortController: null,
  eventSubStatus: 'disconnected',
  shortlistedIds: new Set(),
  hiddenResultIds: new Set(),
  resultsFetchedAt: null,
  searchCandidateCount: null,
  startupIssue: null,
  tokenValidation: null,
  tokenValidationTimer: null,
  raidPermissionEnabled: false,
  raidActionInProgress: false,
};
